### ISSUE TITLE
error while compling 

### ISSUE THREAD

**Issue by gunaveeramallu** [JaewonAC/mpu6050test#1]
07-27 16:18:41.780 3303-3303/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.jaswanth.myapplication, PID: 3303
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/things/pio/PeripheralManagerService;
        at mechasolution.mpu6050.mpu6050.open(mpu6050.java:111)
        at mechasolution.mpu6050.mpu6050.open(mpu6050.java:107)
        at com.example.jaswanth.myapplication.MainActivity.onCreate(MainActivity.java:63)
        at android.app.Activity.performCreate(Activity.java:7010)
        at android.app.Activity.performCreate(Activity.java:7001)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.things.pio.PeripheralManagerService" on path: DexPathList[[zip file "/system/framework/com.google.android.things.jar", zip file "/data/app/com.example.jaswanth.myapplication-UBsRVcM7x8nxURAkmv1XpQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.jaswanth.myapplication-UBsRVcM7x8nxURAkmv1XpQ==/lib/arm, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at mechasolution.mpu6050.mpu6050.open(mpu6050.java:111) 
        at mechasolution.mpu6050.mpu6050.open(mpu6050.java:107) 
        at com.example.jaswanth.myapplication.MainActivity.onCreate(MainActivity.java:63) 
        at android.app.Activity.performCreate(Activity.java:7010) 
        at android.app.Activity.performCreate(Activity.java:7001) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
07-27 16:18:41.796 3303-3303/? I/Process: Sending signal. PID: 3303 SIG: 9

**Comment by stefanvladvoinea** [comment]
PeripheralManagerService was renamed to PeripheralManager
